// Uses real PNG alpha hulls generated by prepare_rig_hulls.py, never DOM rectangles.
const fs = require('node:fs');
(async()=>{
const {createServer}=await import('vite');
const server=await createServer({configFile:false,server:{middlewareMode:true,watch:null}});
try {
const {petFrame} = await server.ssrLoadModule('/src/renderer/rig/pet-frame.ts');
const {ACTIONS,CONTACT_BOUNDARIES} = await server.ssrLoadModule('/src/renderer/rig/actions.ts');
const {CARE_DURATION_MS}=await server.ssrLoadModule('/src/shared/care.ts');
const {SAMPLE_IDS,SAMPLE_TIMING} = await server.ssrLoadModule('/src/renderer/rig/sample-actions.ts');
const {DISPLAY,STAGES,transform} = await server.ssrLoadModule('/src/renderer/rig/geometry.ts');
const {findInventoryItem} = await server.ssrLoadModule('/src/shared/catalog.ts');
const {OUTFIT_IDS,outfitSpec,attachmentDrawables}=await server.ssrLoadModule('/src/renderer/rig/attachments.ts');
const {TRAVEL_IDS,travelDrawables}=await server.ssrLoadModule('/src/renderer/rig/travel.ts');
const {dragVisualForMovement}=await server.ssrLoadModule('/src/renderer/drag-visual.ts');
const hulls=JSON.parse(fs.readFileSync('tmp/rig-evidence/alpha-hulls.json','utf8'));
const failures=new Map(); let frames=0;
function check(input) {
  const {stage,direction,timeMs}=input;const itemId=input.careAction??input.itemId??input.kind;
  const frame=petFrame(input,null,findInventoryItem(input.itemId)?.useVisual.expression??'neutral','/assets'); frames++;
  const attachments=[...OUTFIT_IDS.flatMap(id=>attachmentDrawables(outfitSpec(stage,id),id,frame.pose.body,direction,'/assets/outfits')),...TRAVEL_IDS.flatMap(id=>travelDrawables(stage,id,frame.pose.body,direction,'/assets').map(part=>({...part,id:id+part.id})))];
  for(const part of [...frame.drawables,...attachments]) {
   if(!part.src || part.opacity===0)continue;
   const hull=hulls[part.src.slice(1)]; if(!hull)throw Error('Missing hull '+part.src);
   const d=DISPLAY[stage]; const bounds=[Infinity,Infinity,-Infinity,-Infinity];
   for(const [x,y] of hull) {const p=transform(part.matrix,{x,y}); const px=d.x+p.x*d.size/512,py=d.y+p.y*d.size/512; bounds[0]=Math.min(bounds[0],px);bounds[1]=Math.min(bounds[1],py);bounds[2]=Math.max(bounds[2],px);bounds[3]=Math.max(bounds[3],py);}
   if(bounds[0]<2 || bounds[1]<2 || bounds[2]>218 || bounds[3]>218) {
    const key=[stage,direction,itemId,part.id].join('/');
    if(!failures.has(key))failures.set(key,{key,timeMs,bounds});
   }
  }
}
for(const stage of STAGES) for(const direction of ['left','right']) for(const intensity of ['gentle','normal','lively']) for(const reduced of [false,true]) {
 for(const [careAction,limit] of Object.entries(CARE_DURATION_MS))for(const careVariant of [0,1,2]) {
  const duration=limit??18000;
  const times=new Set([0,.04,.18,.22,.27,.3,.34,.42,.48,.49,.56,.65,.7,.71,.76,.8,.83,.85,.98,1].flatMap(p=>[-.001,0,.001].map(d=>Math.max(0,p*duration+d))));
  for(let t=0;t<=duration;t+=1000/60)times.add(t);
  for(const timeMs of times)check({stage,direction,itemId:null,kind:'care',careAction,careVariant,timeMs,durationMs:limit,sequenceId:1,intensity,reduced,moving:false});
 }
 if(process.argv.includes('--care-only'))continue;
 for(const [itemId,spec] of Object.entries(ACTIONS)) {
  const duration=SAMPLE_IDS.includes(itemId)?findInventoryItem(itemId).useVisual.durationMs:spec.cycleMs;
  const times=new Set([0,.25,.5,.75,1,...CONTACT_BOUNDARIES].flatMap(p=>[-.001,0,.001].map(e=>Math.max(0,p*spec.cycleMs+e))));
  for(let t=0;t<=duration;t+=1000/60)times.add(t);
  if(SAMPLE_IDS.includes(itemId))for(const boundary of [SAMPLE_TIMING.enterMs*.3,SAMPLE_TIMING.enterMs,duration-SAMPLE_TIMING.closeMs,duration-SAMPLE_TIMING.closeMs*.3,duration-SAMPLE_TIMING.closeMs*.1,duration])for(const delta of [-.001,0,.001])times.add(boundary+delta);
  for(const timeMs of times)check({stage,direction,itemId,kind:'inventory-use',timeMs,sequenceId:1,intensity,reduced,moving:false});
 }
 for(const kind of ['idle','nearby','petting','dodge','landing','keyboard-typing','keyboard-rest','cursor-paw','cursor-tug','cursor-chase','cursor-dizzy']) {
  for(let timeMs=0;timeMs<=3000;timeMs+=1000/60)check({stage,direction,itemId:null,kind,timeMs,sequenceId:1,intensity,reduced,moving:kind==='idle'});
 }
 for(const dx of [-240,0,240])for(const dy of [-240,0,240])check({stage,direction,itemId:null,kind:'dragging',timeMs:500,sequenceId:1,intensity,reduced,moving:false,drag:dragVisualForMovement(dx,dy,100,intensity)});
}
fs.writeFileSync('tmp/rig-evidence/bounds.json',JSON.stringify({frames,failures:[...failures.values()]},null,2));
console.log(JSON.stringify({frames,failed:failures.size,examples:[...failures.values()].slice(0,20)},null,2));
process.exitCode=failures.size?1:0;
} finally {await server.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
